services:

  microservice-main:
    build:
      context: ../microservices/main
    container_name: main-microservice-main
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db